### ISSUE TITLE
2 way sync

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#34]
Two way sync:

Sometimes other team members make changes or add new content, and I am notified about them through confluence.  It would be great to be able to sync those back to Obsidian, before continuing to work on the page.

**Comment by andymac4182** [comment]
This will be hard due to the fact there isn't a 1 to 1 conversion from ADF to Markdown. This would mean there is some things that can be created in Confluence that can't be brought back to Obsidian. 

Will have a think about what this would look like to support something like this. It might be a bit later though sorry due to wanting to get the fundamentals of the code and features a bit cleaner before pushing some of the more complex issues.

**Comment by jvsteiner** [comment]
Others might have different opinions, but for me, the main thing is the text.  Even that is harder than it might seem, since you'd have to figure out whether the document makes any sense with those elements omitted.  Plus, if you synced back, made _further_ changes and then republished (which is the main reason for doing it in the first place) then you'd blow away the "Confluence only" content.  I get that it's not trivial.

**Comment by jvsteiner** [comment]
As a workaround, or intermediate step, it might be good enough to simply check that the last changes to the page being published were made by me, and stop publishing if not.  This wouldn't sync anything, but at least it would prevent me from accidentally overwriting content produced by a team member.

**Comment by andymac4182** [comment]
Closing off as logged https://github.com/obsidian-confluence/obsidian-confluence/issues/71
Syncing from Confluence to Obsidian is in https://github.com/obsidian-confluence/obsidian-confluence/discussions/65
