### ISSUE TITLE
Publishing an unchanged version when there are user comments removes the comments

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#63]
Ideally, unless the changed text replaces the entire text that is the subject of the comment (highlighted, usually) the comment should not be removed.  Current behavior is, even if no changes are made, the comments get blown away.

**Comment by andymac4182** [comment]
This is on the list to resolve best I can. At the moment the plugin publishes the content after conversion the ADF (https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/) Confluence returns comments as part of ADF so that removes the comments from being displayed.

Currently the thinking I have is to grab all comments (potentially just unresolved ones) in the page just before publish and adding a section to the bottom with all the inline comments. FYI Page comments are always good to go already its just inline comments that have this issue.

I also want to add tests and improve the compatibility between the ADF generated by https://atlaskit.atlassian.com/packages/editor/editor-json-transformer and what Confluence returns to stop publishing pages for changes that is just a difference in how the two systems generate ADF. This is on the list to do once I get a few more initial functional features sorted.

**Comment by andymac4182** [comment]
Started on https://github.com/obsidian-confluence/obsidian-confluence/pull/164

**Comment by andymac4182** [comment]
Next version will have the feature that does its best to handle this. 

I have also created some documentation for this though it wasn't easy so probably isn't super easy to understand at this point. 
https://obsidian-confluence.com/features/comment-handling.html

**Comment by andymac4182** [comment]
https://github.com/obsidian-confluence/obsidian-confluence/releases/tag/3.7.0 includes this work
